baseURL = "https://mmortall.github.io/blogs-Mind-Journal/"
DefaultContentLanguage = "en" # Theme's display language, supports: en, fr, zh, zh-hant
languageCode = "en-us"
title = "A Hugo Site"
copyright = "Sergii Taraban"
#theme = "diary"
theme="hugo-clarity"

[params.author]
  name = "Sergii Taraban"
  bio = "IT engineer, researcher"

defaultContentLanguage = "en"
defaultContentLanguageInSubdir = true
[languages]
  [languages.en]
    title = "Sytrizm - politico-philosophical concept and model of state organization based on the balance of three sources of power: human institutions, artificial intelligence, and direct democracy"
    languageName = "English"
    weight = 1
  [languages.ru]
    title = "Сайтризм — политико-философская концепция и модель государственного устройства, основанная на равновесии человеческих институтов, искусственного интеллекта и прямой демократии"
    languageName = "Русский"
    weight = 2

# Generate sitemap in the public folder
[sitemap]
  changefreq = "always"
  filename = "sitemap.xml"
  priority = 0.5

# Google Analytics
[services]
  [services.googleAnalytics]
    id = "G-T31NEGXNGS"  # Your Google Analytics ID

[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = "perldoc"
    tabWidth = 4

[params]
subtitle = "Themed by Diary."
enableGitalk = false
enableGiscus = true
showAuthor = true
languageMenuName = "Language"
customCSS = ["css/custom.css"] # Include custom CSS files
pinFeatured = true
numberOfPinnedPosts = 5
enableSearch = true
ga_analytics = "G-T31NEGXNGS"

[params.header.navbar]
show_translations = true
show_language = true

# Microsoft Clarity (https://clarity.microsoft.com/) is a free user behavior recording and analytics tool
clarity = "abcdefghzd"

# Twitter Card and Open Graph settings
enableOpenGraph = true
enableTwitterCards = true
title = "My Blog" # will set 'og:site_name'
description = "My HomePage Description"  # will set 'og:description'

[params.gitalk]
  owner = "user"
  repo = "repo name"
  client_id = "your client id"
  client_secret = "your client secret"
[taxonomies]
   tag = "tags"
   category = "categories"

[params.utterances]
repo="your repo"
term="[ENTER TERM HERE]"
label="your label"
theme="github-light"

# Please visit https://giscus.app/ to generate settings.
[params.giscus]
    data_repo="username/repo"
    data_repo_id="**************************"    
    data_category="General"
    data_category_id="*********************"
    data_mapping="pathname"
    data_strict="0"
    data_reactions_enabled="1"
    data_emit_metadata="0"
    data_input_position="bottom"
    data_theme="preferred_color_scheme"
    data_lang="en"
    crossorigin="anonymous"


[[menu.main]]
url = "/categories"
name = "Categories"
weight = 2
[[menu.main]]
url = "/tags"
name = "Tags"
weight = 3
[[menu.main]]
url = "/posts"
name = "Archive"
weight = 1
[[menu.main]]
url = "/index.xml"
name = "RSS Feed"
weight = 4